version: "3"

tasks:
  run:
    cmds:
      - |
        echo "
        ███╗   ███╗ ██████╗  ████████╗  █████╗  ██╗      ██╗  ██╗
        ████╗ ████║ ██╔══██╗ ╚══██╔══╝ ██╔══██╗ ██║      ██║ ██╔╝
        ██╔████╔██║ ██████╔╝    ██║    ███████║ ██║      █████╔╝ 
        ██║╚██╔╝██║ ██╔══██╗    ██║    ██╔══██║ ██║      ██╔═██╗ 
        ██║ ╚═╝ ██║ ██║  ██║    ██║    ██║  ██║ ███████╗ ██║  ██╗
        ╚═╝     ╚═╝ ╚═╝  ╚═╝    ╚═╝    ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝
        "
      - sleep 5
      - task: up

  up:
    deps:
      - task: uv
      - task: backend:up
      - task: backend:db

  uv:
    cmds:
      - uv sync
      - uv run main.py

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
